### ISSUE TITLE
jshint to eslint conversion

### ISSUE THREAD

**Issue by newtewt** [medic/cht-conf#137]
We are beginning to use eslint everywhere and replacing jshint. Adding this ticket as a tracking point to convert jshint code to use eslint.

**Comment by kennsippell** [comment]
From #186:

* Enable `"curly": "error",` in .eslintrc
* Enable `"guard-for-in": "error",` in .eslintrc
* `eslint-disable-line no-useless-escape` in `csv-to-docs.js `
* `eslint-disable-next-line no-buffer-constructor` in `attachment-from-file.js`

**Comment by garethbowen** [comment]
This has been done for a while.
