### ISSUE TITLE
compile-app-settings - Nools can't process scripts which `require('moment')`

### ISSUE THREAD

**Issue by kennsippell** [medic/cht-conf#225]
1. Add `require('moment') to `tasks.js` or `targets.js`
1. Run `medic-conf compile-app-settings upload-app-settings`
1. Load webapp

**Expected** Glory
**Observed:** Crash

Invalid rule:
```
VM116315 inbox.js:53997 RuleEngine failed to Initialize Error: Invalid rule definition 
Unable to match { in {   when { c: Contact } then { 
```

When running with `-- --debug`, it gets a bit further: invalid action:
```
...
missing ) after argument list
```

**Comment by garethbowen** [comment]
Is this still an issue?

**Comment by kennsippell** [comment]
@garethbowen Yes.  Nools uses these crazy custom string parsing for its "rules" file syntax. `require('moment')` breaks the nools parser. I was hoping to "fix" it with something like this -- https://github.com/medic/cht-core/issues/5906#issuecomment-561286749

**Comment by jonathanbataire** [comment]
This is a problem when you try to use any libraries things like lodash wont work here as well

**Comment by kennsippell** [comment]
This valid javascript also caused a crash in the system `drugList.split(/[ +]/)`. These bugs are annoying and difficult to debug.

**Comment by garethbowen** [comment]
Note that there will be issues with using `require` in tasks code even once it is technically possible. My main concern is bloating the configuration by inlining too many libs and creating large downloads for users on slow connections. This would be wasteful if those libs are also downloaded for other uses. An alternative approach would be [something like this](https://github.com/medic/cht-core/issues/7824) which would allow app devs to include any custom or 3rd party code in their build and then access it through client side APIs. The advantage of this approach is the library is cached separately so changes in the nools config won't require downloading momentjs/lodash/whatever again. Also the same cached library can be used in other areas of config (eg: forms).

Please reach out if this approach would be useful and we can see about getting it prioritised for release.

**Comment by kennsippell** [comment]
I'd imagine an easy first step would be to combine all partner javascript (contact-summary, tasks/targets, purging) into a single bundle instead of three separate bundles. This is a pretty easy change comparatively and it would mean libs (eg lodash) would be downloaded once instead of up to 3 times as-is current.

Also note cht-conf has a hard-coded bundle size limit currently enforced via terser/webpack stuff.  atm it is non-configurable but imagine this change. Some projects work around it [I believe](https://github.com/medic/cht-conf/compare/increase-package-size).

**Comment by garethbowen** [comment]
At least one project runs in `--debug` mode to get around this limit...

**Comment by kennsippell** [comment]
Can you share which projects specifically. That will help to make a data-driven decision on what to build.

**Comment by garethbowen** [comment]
It's a DTree run project that were exploring how to use ML models in their code. That's what prompted the work on #7824

**Comment by kennsippell** [comment]
This is ready for testing. @garethbowen Would you help put it in an appropriate product board? 

cht-core changes (core@vNext) are in branch `noNools`
cht-conf changes (conf@vNext) are in branch `225-no-nools`

### What's changing?
Based on the bug description this might seem like a quick fix but it is actually a bit of a riskier change in how CHT processes an application's tasks and targets code. 

This changes both `cht-core` and `cht-conf` and so there are a matrix of scenarios involved.

cht-core | cht-conf | comment
vNext | official | regression testing only
official | vNext | regression testing only
vNext | vNext | test for fix + regressions

An application's tasks and targets can be provided to CHT via either legacy (nools.rules.js) or declarative (tasks.js and targets.js) styles.  Both styles are at risk of regression. Only the declarative codepath should have any change in behavior.

### Suggestions on Testing Approach

To test the fix, the steps above + https://github.com/medic/cht-core/issues/6506 are useful and should only pass on vNext + vNext. In this scenario, the potential for regressions are nuanced and some time spent on exploratory testing would be useful. Can you think of some weird tasks or targets which might break this and ensure behavior parity?

For regression testing on the other scenarios: things are _maybe_ more likely to be obviously broken if they are broken. It'd be useful to get some eyes on the scenarios listed above + a combo of legacy/declarative.

**Comment by dianabarsan** [comment]
Sharing link to `cht-conf` vNext: https://github.com/medic/cht-conf/pull/536 
cc @tatilepizs

**Comment by tatilepizs** [comment]
### Test details

**Config:** Default
**Environment:** Local with docker helper script
**Platform:** WebApp
**Browser:** Chrome

---

#### Reproducible using `cht-core:master` and `cht-conf:main`

Adding a `moment` to a task config the app crashes.

<details>
<summary>task.js</summary> 

```.js
module.exports = [
...
{
    name: 'dldj',
    icon: 'follow-up',
    title: 'task.test225',
    appliesTo: 'reports',
    appliesIf: () => function () {
      return moment(new Date()).format('YYYY-MM-DD') === '2023-04-19';
    },
    appliesToType: ['pregnancy'],
    actions: [{ form: 'referral_follow_up' }],
    events: [{ days: 0, start: 3, end: 7 }],
    resolvedIf: () => false,
  }
];
```

</details>

<details>
<summary>Image attached</summary> 

![image](https://user-images.githubusercontent.com/94494491/233207536-aee43b4b-91df-4409-88d1-67c5bd0410f8.png)

</details>

---

#### Test 1 - Sanity check ❌ 

**cht-core version:** `master`
**cht-conf version:** `225-no-nools` 

I had two tasks already created (see image tasks_created) and when I uploaded the default [task.js](https://github.com/medic/cht-core/blob/master/config/default/tasks.js) file the app crashed and it shows the following error.

<details>
<summary>Image tasks_created</summary> 

![image](https://user-images.githubusercontent.com/94494491/233211179-5755870e-24b2-405a-aa23-1d7c2779d4af.png)

</details>

<details>
<summary>Error log</summary> 

```
Error getting tasks for all contacts Error: Error parsing !function(e){
...
}
 at A (main.js?_sw-precache=032e4f1841e1e710eff205c292643bb7:1:2298980)
    at M.parse (main.js?_sw-precache=032e4f1841e1e710eff205c292643bb7:1:2299281)
    at M.parseRuleSet (main.js?_sw-precache=032e4f1841e1e710eff205c292643bb7:1:2298672)
    at M.parse (main.js?_sw-precache=032e4f1841e1e710eff205c292643bb7:1:2218639)
    at R (main.js?_sw-precache=032e4f1841e1e710eff205c292643bb7:1:2242941)
    at M.compile (main.js?_sw-precache=032e4f1841e1e710eff205c292643bb7:1:2243259)
    at Object.initialize (main.js?_sw-precache=032e4f1841e1e710eff205c292643bb7:1:2340443)
    at Object.initialize (main.js?_sw-precache=032e4f1841e1e710eff205c292643bb7:1:2335652)
    at Object.initialize (main.js?_sw-precache=032e4f1841e1e710eff205c292643bb7:1:2332657)
    at main.js?_sw-precache=032e4f1841e1e710eff205c292643bb7:1:674983
```

</details>

<details>
<summary>Error image attached</summary> 

![image](https://user-images.githubusercontent.com/94494491/233212614-10cc3230-ce65-48b8-b611-14904b782085.png)

</details>

---

#### Test 2 - Sanity check ✅ 

**cht-core version:** `noNools `
**cht-conf version:** `main` 

Uploading the default task config and generating pregnancy tasks worked as expected

<details>
<summary>Image attached</summary> 

![image](https://user-images.githubusercontent.com/94494491/233228944-0424c693-ec53-4346-abb0-f378449413e8.png)

</details>

---

#### Test 3 - Fix

**cht-core version:** `noNools `
**cht-conf version:** `225-no-nools` 

Uploading the default task config and generating pregnancy tasks worked as expected.
And adding the task config provided by Kenn the app works as expected

<details>
<summary>task.js</summary> 

```.js
module.exports = [
...
{
  name: 'dldj',
  icon: 'follow-up',
  title: 'task.test225',
  appliesTo: 'reports',
  appliesIf: () => 'http://www.foo.com',
  appliesToType: ['pregnancy'],
  actions: [{ form: 'referral_follow_up' }],
  events: [{ days: 0, start: 3, end: 7 }],
  resolvedIf: () => false,
}
];
```

</details>

<details>
<summary>Image attached</summary> 

![image](https://user-images.githubusercontent.com/94494491/233229879-cfa52a16-457e-4ed4-ba09-70543e163a0b.png)

</details>

---

Test failed :x:
Moving the ticket back to `In Progress`.
@kennsippell can you please check?

**Comment by kennsippell** [comment]
@tatilepizs. Thanks for finding this and my apologies for a bit of sloppy prep on my side.  If you pull the latest changes to cht-conf#225-no-nools the bug should be fixed. Also there is a change in the cht-core branch so ensure you redeploy core@vNext before testing those scenarios.

**Comment by tatilepizs** [comment]
### Test details

**Config:** Default
**Environment:** Local with docker helper script
**Platform:** WebApp
**Browser:** Chrome

---

#### Test 1 - Sanity check ✅ 

**cht-core version:** `master`
**cht-conf version:** `225-no-nools` 


Uploading the default task config and generating pregnancy tasks worked as expected

<details>
<summary>Image attached</summary> 

<img width="689" alt="image" src="https://user-images.githubusercontent.com/94494491/234388517-11333b00-18c0-41e7-a1e2-1b8efc1eb6c5.png">

</details>

---

#### Test 2 - Sanity check ✅ 

**cht-core version:** `noNools `
**cht-conf version:** `main` 

Uploading the default task config and generating pregnancy tasks worked as expected

<details>
<summary>Image attached</summary> 

![image](https://user-images.githubusercontent.com/94494491/233228944-0424c693-ec53-4346-abb0-f378449413e8.png)

</details>

---

#### Test 3 - Fix ✅ 

**cht-core version:** `noNools `
**cht-conf version:** `225-no-nools` 

Uploading the default task config and generating pregnancy tasks worked as expected.
And adding the task config provided by Kenn the app works as expected

<details>
<summary>task.js</summary> 

```.js
module.exports = [
...
{
    name: 'dldj',
    icon: 'follow-up',
    title: 'task.test225',
    appliesTo: 'reports',
    appliesIf: () => function () {
      return moment(new Date()).format('YYYY-MM-DD') === '2023-04-19';
    },
    appliesToType: ['pregnancy'],
    actions: [{ form: 'referral_follow_up' }],
    events: [{ days: 0, start: 3, end: 7 }],
    resolvedIf: () => false,
  }
];
```

</details>

<details>
<summary>Image attached</summary> 

![image](https://user-images.githubusercontent.com/94494491/234393730-fb5a6c00-e858-449e-b4f1-9b0e63e7f864.png)


</details>

---

Test passed successfully. :white_check_mark:
Moving the ticket to `Ready to Merge`
@kennsippell

**Comment by kennsippell** [comment]
Thanks @tatilepizs . I actually pushed another change to the cht-core branch... it should only impact behavior on cht-conf@vNext + cht-core@vNext.  I'm not sure if it is recommended to AT again? Or if I'm good to merge? Could you let me know?

**Comment by tatilepizs** [comment]
Can you please share the commit? The only one that I am seeing is [this one](https://github.com/medic/cht-core/pull/8065/commits/8a8f301fec1efcfe9db226351ed13d776def6d8c) and it was 3 days ago, and since I tested the ticket two days ago that will mean that when I retested it I was also using the new change.

cht-core PR that I am looking -> [PR #8065](https://github.com/medic/cht-core/pull/8065)

![image](https://user-images.githubusercontent.com/94494491/234919073-24816913-748e-4580-8136-fad17c1359f9.png)

Please let me know if I am looking at the wrong place

**Comment by kennsippell** [comment]
@tatilepizs That is the correct PR and the correct commit. The commit is 3 days old, but I believe the build finished two days ago. I'm fairly certain the build finished after you completed your test. Sorry for the poor coordination from my side - I should have waited for the build to finish before pinging.

**Comment by tatilepizs** [comment]
Ok, let me give it a quick test just to make sure.
Thank you for the update, I will let you know 🙂
