### ISSUE TITLE
Fail compile-app-settings if there is no .eslintrc file

### ISSUE THREAD

**Issue by newtewt** [medic/cht-conf#333]
When running `medic-conf compile-app-settings` we should fail early if there is no `.eslintrc` file when running actions that require it. Otherwise the user is given the error below and it is not very clear what is needed to correct. 

```
    ERROR in ./tasks.js
    Module Error (from ../medic-conf/node_modules/eslint-loader/dist/cjs.js):
    
    /home/newt/dev/test-medic-conf-dir/tasks.js
      1:1  error  'module' is not defined  no-undef

```

**Comment by garethbowen** [comment]
Alternatively investigate if there's a way to provide a default eslint config so the app builder only needs to create it if they want to change the default.

**Comment by newtewt** [comment]
With the proposed solution from @garethbowen  we should also ensure that if a user is trying to apply standard of default configs from cht-core. Eslintrc should respect the default config and not go looking at parent directories for estlintrc files.

**Comment by njogz** [comment]
Ready for AT on `333-fail-compile-app-settings-if-there-is-no-eslint-file`

**Comment by meghna-khemka** [comment]
Tested above issue
![image](https://user-images.githubusercontent.com/84743933/132784307-51501482-c45b-4cbf-854b-9c7d9acea950.png)

**Comment by meghna-khemka** [comment]
Tested with index.js and issue seems to be working fine.
![image](https://user-images.githubusercontent.com/84743933/132895312-ec019063-435f-4742-9167-832307fa3226.png)
