### ISSUE TITLE
Check to make sure CHT instance is up, give user helpful error if not

### ISSUE THREAD

**Issue by mrjones-plip** [medic/cht-conf#380]
**Is your feature request related to a problem? Please describe.**
When you're doing development and forget to start your CHT instance (either `docker-compose` or `node server.js`) and call `medic-conf`, you can't tell what's going on from the error message:

```
Unable to fetch xml attachment of doc with id form:death_report, returned status code = undefined
```

**Describe the solution you'd like**
We should check that the CHT instance is up first before trying to make API calls against it. If it is not up, we should tell the user with a helpful error message.  Possibly, "CHT Instance at address `http://domain.com` is not responding. Maybe you entered the wrong URL, wrong port or the  instance is not started? Please check and try again."

**Describe alternatives you've considered**
A pre-flight checklist before calling `medic-conf` one of which is "Dev instance on"

**Additional context**
Steps to reproduce this:
1. install `medic-conf`
2. go into `cht-core` repo into the [default config dir](https://github.com/medic/cht-core/tree/master/config/default)
3. Run this command with an intentionally bad port: `medic-conf --url=http://admin:pass@localhost:59883/medicmedic upload-app-forms -- death_report`

**Expected:** Get a nice error telling you "CHT Instance not responding on `http://localhost:59883`. Maybe you entered the wrong URL, wrong port or the instance is not started? Please check and try again"
**Actual:** you get this error:
```
➜  default git:(master) ✗ medic-conf --url=http://admin:pass@localhost:598834242432423/medicmedic upload-app-forms -- death_report
INFO Processing config in default. 
INFO Actions:
     - upload-app-forms 
INFO Starting action: upload-app-forms… 
INFO Preparing form for upload: death_report.xml… 
INFO No media directory found at /home/mrjones/Documents/MedicMobile/cht-core/config/default/forms/app/death_report-media for form /home/mrjones/Documents/MedicMobile/cht-core/config/default/forms/app/death_report.xml 
ERROR Error: Unable to fetch xml attachment of doc with id form:death_report, returned status code = undefined
    at Object.preUploadForm (/usr/lib/node_modules/medic-conf/src/lib/warn-upload-overwrite.js:186:13)
    at processTicksAndRejections (internal/process/task_queues.js:97:5) 
```

**Comment by njogz** [comment]
> I think in this case, if we can't tell, we should show a more useful message and then prompt the user to confirm rather than just exiting.
> 


@garethbowen if we already confirm that the server is up but still encounter an unexpected error do you still think we should prompt the user? I think with the server check we should still throw an error and exit.

**Comment by garethbowen** [comment]
Yeah with an unexpected error I think it makes sense to output all the information we know about and exit. The key is to gracefully handle as many expected errors (like the server being down) as we can.
