### ISSUE TITLE
Add an action to change contact types in bulk

### ISSUE THREAD

**Issue by dianabarsan** [medic/cht-conf#408]
**Is your feature request related to a problem? Please describe.**
Some projects (especially older projects that need to adapt to new workflows) need hierarchy changes, including changing contact types. 
Currently, there is no tool that helps achieve this.

**Describe the solution you'd like**
Given that these changes are often very heavy (lots of docs need updates), and sometimes also require contacts being moved, the action could support editing docs that are already on disk, and serve as a complement to `move-contacts`. Ideally, contacts shouldn't be changed twice. 
Alternatively, it could be stand-alone, but should function like `move-contacts`, download docs, make edits and save on disk. 

**Describe alternatives you've considered**
Don't integrate into medic-conf, just write a script to achieve this. 

**Additional context**
Because of logistic pains, many projects will opt for a branch-by-branch updates, which means that projects must support two hierarchies at the same time. Depending on needs, there is a potential that all contacts from an instance have to be updated to use a new type.

**Comment by binokaryg** [comment]
Some alternatives we have considered:
- Using the [`edit-contacts`](https://github.com/medic/medic-conf#editing-contacts-across-the-hierarchy) action after removing `type` from the [`RESERVED_COL_NAMES`](https://github.com/medic/medic-conf/blob/4df71f3d0f6039da978e3688cc7b9a5587526e19/src/fn/csv-to-docs.js#L12)
- Using `jq`:
e.g. `jq  'if (.type == "district_hospital") then .type = "contact", .contact_type = "c30_supervisor_area" else . end' docs.json`
- Using `sed`:
e.g. `find json_docs -name \*.json -exec sed -i -r "s/\"type\": ?\"district_hospital\"/\"type\":\ \"contact\",\n\ \ \"contact_type\":\ \"c30_supervisor_area\"/g" {} \;`

Wishes:
- It would be nice to get a summary of changes after running it.
e.g. type changed from 'x' to 'y' in _n_ number of docs
- Can we also optionally get similar numbers before actually changing the docs? Will it be too costly for a large number of docs?
e.g. type will be changed from 'x' to 'y' in _n_ number of docs
- Can we get an estimate of the time that will be required to process all the docs?

**Comment by dianabarsan** [comment]
I think using `jq` or `sed` are very risky, I would advise against it. I'm sure our app developers can handle it just fine, but we have an issue to devise steps and provide tools to support hierarchy changes for the broad community: https://github.com/medic/cht-core/issues/6751 . 

`edit-contacts` doesn't work with already "downloaded" docs. I think the best we could do is edit it and add an additional parameter that tells it to work with json files that are already downloaded and edit those directly. 
Additionally, we could update `move-contacts` to do the same, so they can be used interchangeably. 

I think the tool (whatever it ends up being) should provide as much support as possible, to insure a correct data schema, so if we remove `type` from `RESERVED_COL_NAMES`, or add a tool that changes contact types, it should cross-check with the config and make sure that the type exists, if it's hardcoded or needs `type: contact` and so on.

**Comment by njogz** [comment]
I started work on this and going with the recommendation by Diana above to change the `edit-contacts` command to be able to change the contact type and also work with downloaded json files.

**Comment by Fatoufall** [comment]
just curious, does this feature will require Muso to upgrade to the latest version? also any idea on the release date?

**Comment by njogz** [comment]
@Fatoufall no upgrade cht-core is required for this feature. There is no definite release date yet. It will be part of the [3.7](https://github.com/medic/cht-conf/milestone/1) release.

**Comment by Fatoufall** [comment]
@dianabarsan can you help figure out as this is linked to one of our priorities WF to deploy in the field?
cc @craig-landry @kennsippell

**Comment by dianabarsan** [comment]
We will do our best to get this ready by the time it is needed. What is the timeline of the deployment / preparation?

**Comment by binokaryg** [comment]
According to the work plan, the rehearsal for the hierarchy update starts on 13/09/2021.

**Comment by njogz** [comment]
@binokaryg and I tested tested the proposed solution with 10894 docs (10478 contacts) in a dev clone. It worked great without any hiccups. We are planning on another test with a larger sample size.
