### ISSUE TITLE
cht-conf fails in docker: SyntaxError: Unexpected token 

### ISSUE THREAD

**Issue by mrjones-plip** [medic/cht-conf#448]
**Describe the bug**
When [following the steps](https://github.com/medic/cht-conf/#docker) to launch cht-conf in docker, I get an error that prevents me from using cht-conf

**To Reproduce**
1. Clone `cht-conf` [repo](https://github.com/medic/cht-conf/) to your machine, ensure you're `master`
2. `cd` into the `cht-conf`
2. Build the docker image locally: `docker build -t cht-conf:v0 .`
3. Create a container from the new image: `docker run cht-conf:v0`
4. In another terminal, pull up a shell on the container `docker exec -it <container_name> /bin/bash`
5. Run `cht`

**Expected behavior**
I can run `cht` without errors

**Logs**
```
$ docker run -d cht-conf:v0 

a324e8728b17fa6a6369ab68d960b132f54cf5e765d61bf49eeb6c942a21ecea

$ docker ps
CONTAINER ID   IMAGE         COMMAND               CREATED         STATUS         PORTS     NAMES
a324e8728b17   cht-conf:v0   "tail -f /dev/null"   4 seconds ago   Up 3 seconds             mystifying_keldysh

$ docker exec -it mystifying_keldysh /bin/bash
root@a324e8728b17:/# cht
/usr/lib/node_modules/cht-conf/src/bin/index.js:8
(async () => {
       ^

SyntaxError: Unexpected token (
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:549:28)
    at Object.Module._extensions..js (module.js:586:10)
    at Module.load (module.js:494:32)
    at tryModuleLoad (module.js:453:12)
    at Function.Module._load (module.js:445:3)
    at Module.runMain (module.js:611:10)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:160:9)
```

**Environment**
- Instance: NA (none)
- Client platform: Ubuntu 20.04, Docker version 20.10.9, build c2ea9bc
- cht-conf version: 3.9.0 
- cht-core version: NA (none)

**Additional context**
There were a lot of errors when building the image, maybe they're related? Attaching complete output from `docker build -t cht-conf:v0 . > build.log`: [build.log.zip](https://github.com/medic/cht-conf/files/7500686/build.log.zip)

**Comment by ngaruko** [comment]
LGTM.
Tested following the[ steps above](https://github.com/medic/cht-conf/issues/448#issue-1048017825). On `master`, `cht` command throws an error:
```
➜  cht-conf git:(master) ✗ docker exec -it 242027a7b753 /bin/bash
root@242027a7b753:/# cht
/usr/lib/node_modules/cht-conf/src/bin/index.js:8
(async () => {
       ^

SyntaxError: Unexpected token (
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:549:28)
    at Object.Module._extensions..js (module.js:586:10)
    at Module.load (module.js:494:32)
    at tryModuleLoad (module.js:453:12)
    at Function.Module._load (module.js:445:3)
    at Module.runMain (module.js:611:10)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:160:9)
root@242027a7b753:/# 
```
on the branch, no errors:
```
 cht-conf git:(448-update-dockerfile-and-docs) ✗ docker exec -it ffbb95683570 /bin/bash
root@ffbb95683570:/# cht

NAME
  cht - Configure your CHT instances

SYNOPSIS
  cht <--local|--instance=instance-name|--url=url>
Or:
  cht <--local|--instance=instance-name|--url=url|--archive> <actions> <options> -- <params>

DESCRIPTION
  This script updates and uploads a project's configuration.

SUPPORTED ACTIONS
  * backup-all-forms
  * backup-app-settings
  * check-for-updates
.........
```
Feel free to merge @mrjones-plip
