### ISSUE TITLE
Move CD user from  garethbowen to robot

### ISSUE THREAD

**Issue by mrjones-plip** [medic/cht-conf#452]
**Describe the issue**
Recently we moved the release process for this repo to a CD one - [it works great](https://github.com/medic/cht-conf/issues/448#issuecomment-970579517)! However, the release is done under the `garethbowen` user.  At some point this user may leave Medic at which point the CD would break

**Describe the improvement you'd like**
We should move the CD to a non-human robot user dedicated to doing CD for this repo (or other repos too?)

**Describe alternatives you've considered**
Wait until the user leaves and fix it then :cry:

**Comment by garethbowen** [comment]
I've granted the medic-ci user admin access over cht-conf, and generated an access token for that user. This should now be fixed but we'll have to wait for the next release to confirm.
