### ISSUE TITLE
Instance verification checks wrong url

### ISSUE THREAD

**Issue by ngaruko** [medic/cht-conf#460]
**Describe the bug**
`cht` fails url verification with errors below.
**To Reproduce**
Steps to reproduce the behaviour:
1. Install cht-conf ( 3.8 and above)
2. Run cht --url =<yourUrl>
3. See error with `/medic/` appended to the end of the `yourUrl`

**Expected behavior**
Instance should be verified against url as submitted without the additional `medic/`
**Logs**
```
 node src/bin/index.js --url=https://gamma-cht.dev.medicmobile.org/
WARN Project has no dependency on cht-conf. 
INFO Checking that https://gamma-cht.dev.medicmobile.org/medic/ is available... 
ERROR Failed to get a response from https://gamma-cht.dev.medicmobile.org/medic/. Maybe you entered the wrong URL, wrong port or the instance is not started? Please check and try again
```

**Screenshots**
![image](https://user-images.githubusercontent.com/6979995/146091023-68cad963-3ea6-49e3-9170-3f8c6fa8a484.png)
**Environment**

- cht-conf version: (3.8.0 and above)

**Additional context**
My suspicion is that the error is on this https://github.com/medic/cht-conf/pull/437/files#diff-f17bc036cb59910f33d92d2f663c324b1eed04c21c9e9ef6b5eef547c75688ffR96 -  const url = `${environment.apiUrl}/`; should be probably be `environment.instanceUrl . The first is like https://gamma-cht.dev.medicmobile.org/medic and the second (correct one I guess is https://gamma-cht.dev.medicmobile.org/).

**Comment by dianabarsan** [comment]
The url ending with /medic should also work fine. 
We're not expecting an answer, just a 2xx status code. 

Did you use appropriate authentication when passing the url to cht-conf?

**Comment by dianabarsan** [comment]
Confirming that this happens when authentication is missing from the url parameter. 

I think the right solution here is to change the message to prompt the user to check the authentication portion of the url.

**Comment by ngaruko** [comment]
Steps to test on local:

1.  make sure you have a running instance (say https://localhost)
2. clone this repo
3. `cd cht-conf`
4. `npm install`
5. while still on `master`, cd into a folder with an `app_settings.json` file (could be `cht-core/config/default`, just pay attention to the relative path to `cht-conf` ) and run `node <path-to-cht-conf>/cht-conf/src/bin/index.js --url=https://localhost`
6. Observe error as in [description](https://github.com/medic/cht-conf/issues/460#issue-1080368516) above
7. Now in cht-conf, `checkout 460-better-error-messages`
8. run `node <path-to-cht-conf>/cht-conf/src/bin/index.js --url=https://localhost`
9. You should see a different error message in line with the [PR](https://github.com/medic/cht-conf/pull/461/commits/e9ce61bc36f79c1712f0a8a8d71a6817dd028651)
10. Try a combination of no credentials at all and wrong credentials and see what happens
11. use the right creds and see if it still works

**Comment by lorerod** [comment]
**Reproducible on master:**
- When missing authentication from the URL parameter, a general error message appears:
<img width="1308" alt="Captura de Pantalla 2021-12-29 a la(s) 11 46 23" src="https://user-images.githubusercontent.com/21312057/147678212-5741b941-4811-4b79-9936-13aeb9e60944.png">

**Fixed on branch:**
- When missing authentication from the URL parameter, a specific error message appears:
<img width="1279" alt="Captura de Pantalla 2021-12-29 a la(s) 11 54 07" src="https://user-images.githubusercontent.com/21312057/147678383-e633e03f-97bf-451c-a70c-1a6903d6412b.png">

- When using a wrong user and password:
<img width="1286" alt="WrongUserWrongPass" src="https://user-images.githubusercontent.com/21312057/147691921-f9759bb7-2f4f-4bec-ab9e-3a5952a8d9a6.png">

- When using an admin user with wrong password:
<img width="1287" alt="correctUserWrongPass" src="https://user-images.githubusercontent.com/21312057/147691961-0fd4367c-dbfa-44da-be9c-21d4bd181965.png">

- When using a non admin user with correct password, an specific message appears:
<img width="1288" alt="NoAdminUserCorrectPass" src="https://user-images.githubusercontent.com/21312057/147692001-11b8c174-79ab-4973-958d-5239b90c3aad.png">

- When using an admin user with correct password, the command works:
<img width="1286" alt="CorrectAdminUserCorrectPassw" src="https://user-images.githubusercontent.com/21312057/147692054-bcf8fb1c-68c2-46e8-aa90-1f72a383741c.png">
