### ISSUE TITLE
Fix eslint warnings

### ISSUE THREAD

**Issue by garethbowen** [medic/cht-conf#465]
**Describe the issue**
We have a number of eslint warnings showing which seemed like a good idea at a time, but now it's just ended up spamming developers and generally being ignored. 

**Describe the improvement you'd like**
These should be fixed to avoid potential bugs, reduce spam, and then the rules should be made strict to make future violations obvious.

**Describe alternatives you've considered**
They could be turned off which stops the spam but leaves the potential bugs.

**Comment by garethbowen** [comment]
For AT: It's hard to test this directly because the only visible difference should be during build time. This has been tested and confirmed by automated checks in CI. However this required significant refactoring, particularly in the error handling code. A good test would be to run through a range of common errors and make sure that the error is handled and communicated in English as well as an error code returned for bot integration.

For example, providing no arguments should produce an error like...

```sh
$ cht
...
ERROR Invalid number of arguments.
$ echo $?
1
```

In this example the `ERROR` is the bit for human consumption. I use `echo $?` to get the response code with `0` for success and everything else (in this case `1`) representing an error.

There are a range of other ways an error should be generated, for example, API being unavailable (down, bad URL, no authentication, etc), or the user aborting the command when prompted. Try a few of these out and make sure the error message is clear and the response code is not `0`.

**Comment by tatilepizs** [comment]
Using branch `465-fix-eslint-warnings` all the errors where shown correctly.

- `cht --`
![image](https://user-images.githubusercontent.com/94494491/155173764-5a5982b3-bae2-45ab-9036-5c8c0380407d.png)
![image](https://user-images.githubusercontent.com/94494491/155173840-80313244-2cc4-429f-b015-99f2237b5016.png)

- `cht --url=https://medic:wrongPassword@127-0-0-1.my.local-ip.co:8443`
![image](https://user-images.githubusercontent.com/94494491/155174338-dd3b046c-abb3-4d1c-abb3-97f6f57bf0d6.png)

- `cht --url=https://wrongUser:password@127-0-0-1.my.local-ip.co:8443`
![image](https://user-images.githubusercontent.com/94494491/155176077-9f15e1b5-beae-4298-a6ad-e86090cf4907.png)

- `cht --url=https://medic:password@127-0-0-1.my.local-ip.co`
![image](https://user-images.githubusercontent.com/94494491/155176240-1d85e23a-801c-4cf3-970b-e7276b93d10c.png)
