### ISSUE TITLE
Unicode character not accepted as form code

### ISSUE THREAD

**Issue by binokaryg** [medic/cht-conf#471]
**Describe the bug**
We use Nepali Unicode characters as form codes. e.g. "क", "अ". These are working fine when placed inside `app_settings.json`. However, if we put them in `forms.json` and try to compile the app settings, we get this error:
```
ERROR Invalid form settings: ValidationError: "क" is not allowed
```

**To Reproduce**
1. Add a form with code `क` to `forms.json`
2. Compile the app: `cht compile-app-settings`
3. See error

**Expected behavior**
Unicode characters and numerals should be accepted.

**Logs**
```
INFO Starting action: compile-app-settings…
INFO Error: Invalid form settings: ValidationError: "क" is not allowed
    at compileAppSettingsForProject (/home/binod/git/cht-conf/src/fn/compile-app-settings.js:70:15)
    at Object.compileAppSettings [as execute] (/home/binod/git/cht-conf/src/fn/compile-app-settings.js:20:25)
    at executeAction (/home/binod/git/cht-conf/src/lib/main.js:220:40)
    at module.exports (/home/binod/git/cht-conf/src/lib/main.js:210:11)
    at /home/binod/git/cht-conf/src/bin/index.js:16:11
    at Object.<anonymous> (/home/binod/git/cht-conf/src/bin/index.js:22:3)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:76:12)
    at internal/main/run_main_module.js:17:47
ERROR Invalid form settings: ValidationError: "क" is not allowed
```

**Screenshots**

**Environment**
- Instance: Any
- Client platform: Any
- cht-conf version: tested with 3.10.1
- cht-core version: Any

**Additional context**
This has to do with the restrictive regex expression used [here](https://github.com/medic/cht-conf/blob/8b9c86842b8643a28e96abc15a2b2ed8bfe83ab2/src/lib/validate-app-settings.js#L4):
https://github.com/medic/cht-conf/blob/8b9c86842b8643a28e96abc15a2b2ed8bfe83ab2/src/lib/validate-app-settings.js#L4

If we make it more inclusive with something like: `/[\p{L}\p{N}]{1,30}/u`, then the problem could be solved.

**Comment by garethbowen** [comment]
@binokaryg Depending on which SMS format you use the form and field name strings are even more permissive allowing things like punctuation so I've made it even more inclusive. What format are SMS messages being received? I assume you've tested the server side parsing with the old `app_settings.json` structure?

**Comment by binokaryg** [comment]
We use TextForms compact e.g. `क 21 Patient Name`.
I haven't tested server-side parsing but we have been using this format with Nepali (Devanagari) form codes for many years with the old `app_settings.json` structure. When I tried to break it into `base_settings.json` and `forms.json`, then I ran into the above problem.

It's good to make it more permissive and allow special characters too. Thanks for the quick fix @garethbowen. :)

**Comment by garethbowen** [comment]
Ready for AT on `471-support-unicode-form-names`

**Comment by ngaruko** [comment]
Did you wanna give it a quick test to confirm, before we close this off @binokaryg ? Thanks

**Comment by binokaryg** [comment]
Confirmed, it works when running from the `471-support-unicode-form-names`. Thanks.

**Comment by ngaruko** [comment]
Thanks @binokaryg - Should be good to merge @garethbowen ✔️
