### ISSUE TITLE
Error when note fields are required in form

### ISSUE THREAD

**Issue by jkuester** [medic/cht-conf#494]
Setting a `note` field to be `required` has always been bad data, but in previous versions of Enketo, this was just silently ignored.  Now, this config will prevent the user from continuing to the next page and completing the form. `cht-core` has been updated, as a part of these changes: https://github.com/medic/cht-core/pull/7256) to automatically  remove the `	required` designation from `note` fields, but best practice would still have us identify these improperly configured notes when compiling the form with `cht-conf` and produce an error so that the user knows to update the config.  See [this script](https://gist.github.com/jkuester/292b0a584f7fc77a7d6c768f3c7c1ba3) as an example of regex for finding required notes and [this xsl code](https://github.com/medic/cht-core/blob/29096c010ea6400021827b9d048cdfeabef91682/api/src/xsl/openrosa2html5form.xsl#L60) which is how `cht-core` is removing the `required` designation.

**Comment by tatilepizs** [comment]
Hi @jkuester, could you please help me with some steps/comments/ideas about what will be the correct way to test it?

**Comment by jkuester** [comment]
Oh sure! Sorry for forgetting to put something in here before.  Basically this new functionality should cause a form to fail validation if there is a `note` field that is required.  

1. Create a form (Form A) with a `note` field (can be any message in the note) where the `required` value is `true()`
2. Create form (Form B) with a `note` field (can be any message in the note) where the `required` value is `false()`
3. Put these forms in `./forms/app`
4. Run `cht convert-app-forms validate-app-forms`  To run with the branch code, you have a couple options:
    1. Checkout the branch and follow [these steps](https://github.com/medic/cht-conf#executing-your-local-branch)
    2. Just globally install the branch directly using `npm i -g medic/cht-conf#494_required_notes` and then you can use the `cht` commands as you would normally (note this method will overwrite any version of cht-conf you have currently installed)
5. See that the validation fails for the `note` in Form A, but not the `note` in Form B.

**Comment by tatilepizs** [comment]
Thanks @jkuesterfor all the details, it was really helpful.

These are the forms that I used -> [enketo_test_formA.xlsx](https://github.com/medic/cht-conf/files/9376074/enketo_test_formA.xlsx) - [enketo_test_formB.xlsx](https://github.com/medic/cht-conf/files/9376088/enketo_test_formB.xlsx)

Testing steps:
* Used the command `npm i -g medic/cht-conf#494_required_notes` to install the correct branch
* Copied the created forms in `./forms/app`
* Run the command `cht convert-app-forms validate-app-forms`
* Validation shown the following message:
![image](https://user-images.githubusercontent.com/94494491/185453949-f5b1e7a5-9ebf-43c1-9393-5ee8b9450486.png)
