### ISSUE TITLE
Add validation to warn when using `horizontal` appearance instead of `columns`

### ISSUE THREAD

**Issue by jkuester** [medic/cht-conf#500]
The `horizontal` and `horizontal-compact` appearances are [deprecated](https://forum.getodk.org/t/spec-proposal-harmonize-compact-compact-n-horizontal-horizontal-compact-appearances/15565/32) in favor of [columns](https://docs.getodk.org/form-question-types/?highlight=column#select-widget-with-columns-pack-appearance). It would be nice to provide a warning with a link to the columns documentation.

Importantly this warning should only displayed if the server version if >= 4.0.  Not sure how possible it will be to access/process the version of the server...

**Comment by tatilepizs** [comment]
Hi @jkuester, could you please help me with some steps/comments/ideas about what will be the correct way to test it?

**Comment by jkuester** [comment]
@tatilepizs Oh sure! Sorry for forgetting to put something in here before.  Basically this new functionality should cause warning to be printed when validating a form that is using the `horizontal` appearance (on questions like `select_one`).    

| old appearance | | new appearance |
| --- | --- | --- |
| horizontal | :arrow_forward:  | columns |
| horizontal-compact | :arrow_forward:  | columns-pack |
| compact | :arrow_forward:  | columns-pack no-buttons |
| compact-n | :arrow_forward:  | columns-n no-buttons |

1. Create a form with two questions:
    1. A `select_one` field with the `horizontal` appearance
    2. A `select_one` field with the `columns` appearance
4. Put these forms in `./forms/app`
6. Run `cht convert-app-forms validate-app-forms`
7. See that the validation succeeds, but a warning is printed for the field with the `horizontal` appearance
8. When you open the form in the webapp, both questions should be displayed the same (they should look the same on the page)

**Comment by jkuester** [comment]
I forgot that this validation is also tied to a specific version of the CHT (`4.0.0`) which is where support was added for the new appearances.  The validation will not run for older versions of the CHT.  Since `4.0.0` is not released yet, we will need to hack things a bit to get the validation to run.

The most authentic way to trigger the run is to just manually set the version of your CHT instance in Couch by using Fauxton to manually edit your `medic` ddoc:
- Go to https://192-168-122-1.my.local-ip.co:8443/_utils/#database/medic/_design/medic (using the url for your instance)
- Update `deploy_info.version` to be `4.0.0` (if there is no `deploy_info` object, then add one)
- Save the doc

Then you should be able to  run the validation when you have specified the URL to that instance:
```
 cht --url=https://medic:password@192-168-122-1.my.local-ip.co:8443 convert-app-forms validate-app-forms
```

**Comment by tatilepizs** [comment]
Thanks @jkuesterfor all the details, it was really helpful.

This is the form that used -> [enketo_test_select_one.xlsx](https://github.com/medic/cht-conf/files/9378059/enketo_test_select_one.xlsx)
 
Testing steps:
* Used the command `npm i -g medic/cht-conf#500_warn_horizontal` to install the correct branch
* Copied the created forms in `./forms/app`
* Updated the `medic` ddoc in Fauxton to manually change the cht deploy version from `master` to `4.0.0` 
   <img width="300" alt="image" src="https://user-images.githubusercontent.com/94494491/185507374-5be57fb8-e975-4a04-bbb0-ea5faa005fc4.png">
* Run the command `cht --url=https://<user>:<password>@127-0-0-1.my.local-ip.co:8443 convert-app-forms validate-app-forms -- enketo_test_select_one`
* Validation shows the following message:
  ![image](https://user-images.githubusercontent.com/94494491/185507765-46ac339e-86a3-4f52-b3b3-b8728942f4a1.png)
