### ISSUE TITLE
cht-conf command to upload models

### ISSUE THREAD

**Issue by njogz** [medic/cht-conf#522]

**Comment by andrablaj** [comment]
@njuguna-n I see this issue on the Ecosystem board. Do you have any context about what this is about? If you don't remember anymore, can we close it?

**Comment by njuguna-n** [comment]
@andrablaj the idea was to have an easy way for app developers to create and upload models to a CHT deployment similar to how it is currently done for form configurations. I think we can close it and open a new issue if such a requirement comes up in the future.
