### ISSUE TITLE
Support simplified app developer environment using a VSCode dev container

### ISSUE THREAD

**Issue by jkuester** [medic/cht-conf#542]
**Is your feature request related to a problem? Please describe.**
Setting up the development environment for developing CHT apps (install node, install nvm, etc etc) can be challenging, time-consuming, error-prone, and tedious.

**Describe the solution you'd like**
Instead of having to have all of the dependency libraries/SDKs installed in the local environment, it would be simpler to just have a [VSCode dev container](https://code.visualstudio.com/docs/devcontainers/containers) with all these dependencies pre-installed.  Then an app developer would simply need to launch their local VSCode workspace inside the dev container and their environment would already be setup and ready to go.

**Describe alternatives you've considered**
- Improving the documentation including multiple OSes
- Distribute a Docker image for app development. 
- a bind mount to the [existing](https://github.com/medic/cht-conf/blob/main/Dockerfile) Dockerfile for cht-conf

**Comment by jkuester** [comment]
After extensive investigation, here are the two alternatives I have found:

- Option 1: [Docker Image](https://containers.dev/implementors/json_reference/#image-specific)
	- Pros:  
		- Self-contained, fully controlled environment  
		- We already have an (outdated) Dockerfile for building the image  
		- More general purpose since the Docker image could be useful outside of a "dev-container" (VSCode) environment  
		- We are already publishing other Docker images  
	- Cons:  
		- Responsible for full stack in the image and keeping it all up to date  
		- No way to make it discoverable in the VSCode dev containers menu  
- Option 2: ["Feature"](https://containers.dev/implementors/features/) containing only  cht-conf and pyxform (builds on existing Node/Python features)  
	- Pros:  
		- Minimal amount of infra to maintain  
		- Can publish it publicly via established process (so that is could be discoverable)  
		- More flexible since it could be combined with additional features/images to build a user's desired workspace  
	- Cons:  
		- Requires a bit more config for each project since they need to specify both the base image plus this feature  
		- Only really useful within a "dev-container" environment. (Not sure there is much support yet outside of VSCode)  

At this point, I am planning to more forwards with `Option 1` for these reasons:

- A general purpose Docker container seems more aligned with our existing direction (we already support building an image) and we can still achieve the desired VSCode functionality without having to support a bespoke "feature"
- At this time, it feels like the discoverablity and flexibility of a feature are not as important as having a simple approach that "just works" (no need to worry about compatibility issues with trying to use the feature with the wrong images)
  - This may change in the future. If app developers start making extensive use of dev containers there may be a desire to support more complex environments where a feature would be super useful. However, I think it makes more sense to start with an image as the MVP and we can look into a feature later if the need arises.

**Comment by jkuester** [comment]
@tatilepizs as we talked about today, this issue is ready for AT on https://github.com/medic/cht-conf/tree/dev-container

Let me know if you have any questions beyond what was discussed earlier!

**Comment by tatilepizs** [comment]
Thank you @jkuester for all the time answering my questions and for all the detail and explanations.

### Test details

#### Creating an empty project

<details>
<summary>Building the image ✅ </summary>

![image](https://user-images.githubusercontent.com/94494491/224106496-d67fe472-61f2-42fb-a99b-757c7cd866d6.png)

</details>

<details>
<summary>Open the workspace inside the container and initialize the project - VS Code ✅ </summary>

![image](https://user-images.githubusercontent.com/94494491/224109387-9f202591-a216-438c-b6e2-1d9f2c42a2a6.png)

</details>

<details>
<summary>Exit the container VS Code ✅ </summary>

![image](https://user-images.githubusercontent.com/94494491/224113074-d757d931-d9a1-4634-926e-44ed71bbc647.png)
![image](https://user-images.githubusercontent.com/94494491/224113265-579ff318-33d2-4a71-a0c5-5d1a463e3225.png)

</details>

<details>
<summary>Standalone Docker utility ✅ </summary>

Using the following command inside the project directory:
```
docker run -it --rm -v "$PWD":/workdir cht-ide initialise-project-layout
```

![image](https://user-images.githubusercontent.com/94494491/224114620-f78f0952-f332-45a3-8adc-660c7f93b814.png)


</details>

---

#### Using an existing config

<details>
<summary>Using the default config to open the container ✅ </summary>

![image](https://user-images.githubusercontent.com/94494491/224131007-3299d569-cf4a-43a2-a5c6-686be67443e0.png)

</details>

<details>
<summary>Uploading the default config to a cht-core instance ✅ </summary>

![image](https://user-images.githubusercontent.com/94494491/224130939-9dfc6e87-b625-44fa-a556-1ea09745e9e0.png)

![image](https://user-images.githubusercontent.com/94494491/224130883-b7a4357a-42b8-4dd3-8eb2-af9858eeaab0.png)

</details>

<details>
<summary>Running tests ✅ </summary>

Using the following command:
```
npm test
```

![image](https://user-images.githubusercontent.com/94494491/224134915-d073a174-e615-43c2-9f64-1a9d09825c98.png)

</details>

---

Everything looks fine, if there is anything else that we should test please let me know 🎉
