### ISSUE TITLE
DOCKER_HUB_PASS does not work for pushing image to Docker Hub

### ISSUE THREAD

**Issue by jkuester** [medic/cht-conf#554]
I am still trying to get a `cht-app-ide` image published.  The latest issue is that the GH actions [workflow fails](https://github.com/medic/cht-conf/actions/runs/4670533148/jobs/8270384070) when trying to login to Docker Hub.

> Logging into Docker Hub...
> Error: Error response from daemon: Get "https://registry-1.docker.io/v2/": unauthorized: please use personal access token to login

It is possible that the normal password for the account does not work here [because 2FA is enabled](https://devcoops.com/docker-error-response-from-daemon-unauthorized-please-use-personal-access-token-to-login/)?  Regardless, I think the fix is to generate a "Personal Access Token" and use that for the `DOCKER_HUB_PASS`.

@garethbowen could you possible update that secret value when you get the chance?

**Comment by garethbowen** [comment]
@jkuester 1pass already had an access token in it so I updated the secret to use it.

**Comment by jkuester** [comment]
6th time is the charm....
