### ISSUE TITLE
upload-extension-libs action throws error when folder doesn't exist

### ISSUE THREAD

**Issue by yrimal** [medic/cht-conf#555]
**Describe the bug**
We recently added `upload-extension-libs` action on cht-conf and this is the default action as well. So, when user doesn't specify any parameters and runs `cht --url=...`, this action is also in

**To Reproduce**
1. Have latest cht-conf installed
2. Go to CHT project where `extension-libs` folder doesn't exist.
3. Run `cht --local` or `cht --local upload-extension-libs`
4. See error. 

**Expected behavior**
Like other actions, it should throw a warning and continue. For example `upload-privacy-policies` or `upload-partners`. 

**Logs**
```
INFO TypeError: Cannot convert undefined or null to object
    at Function.keys (<anonymous>)
    at Object.execute (/usr/local/lib/node_modules/cht-conf/src/fn/upload-extension-libs.js:17:17)
    at executeAction (/usr/local/lib/node_modules/cht-conf/src/lib/main.js:258:40)
    at module.exports (/usr/local/lib/node_modules/cht-conf/src/lib/main.js:193:11)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async /usr/local/lib/node_modules/cht-conf/src/bin/index.js:16:5 
ERROR Cannot convert undefined or null to object 
```
**Environment**
- Client platform: MacOS M1
- cht-conf version: 3.18
- cht-core version: 3.17.1

**Comment by garethbowen** [comment]
Ready for AT on `yrimal:main` (on @yrimal 's fork).

Make sure that the feature still works, but doesn't throw an error when there's no config folder.

**Comment by tatilepizs** [comment]
### Test details

**Config:** Default
**Environment:** Local
**Platform:** WebApp
**Browser:** Chrome

---

### Reproducible on `master`

<details>
<summary>cht --local</summary>

![image](https://user-images.githubusercontent.com/94494491/233699738-eabb2ae5-7a75-401a-a00f-7bcec8eea81c.png)

</details>

<details>
<summary>cht --local upload-extension-libs</summary>

![image](https://user-images.githubusercontent.com/94494491/233699901-10515714-64ad-47a5-b1e9-4cf8c2b0e7cd.png)

</details>


### Fixed on [`yrimal:main`](https://github.com/yrimal/cht-conf)

<details>
<summary>cht --local</summary>

![image](https://user-images.githubusercontent.com/94494491/233702403-f54bd200-c0b5-40b7-9ee2-52b60dd3cb37.png)

</details>

<details>
<summary>cht --local upload-extension-libs</summary>

![image](https://user-images.githubusercontent.com/94494491/233702663-ee0faafe-bd4c-4d01-9384-d098832a3f26.png)

</details>


### [`extension-libs`](https://github.com/medic/cht-core/issues/7824) functionality is still working as expected.

<details>
<summary>Images attached</summary>

![image](https://user-images.githubusercontent.com/94494491/233717746-5288562a-6de2-48c0-977a-83617f9d06bd.png)
![image](https://user-images.githubusercontent.com/94494491/233718009-3656f49a-1b85-4a5f-8f8a-8ff2137ea360.png)

</details>

---

Test passed successfully. :white_check_mark:
Moving the ticket to `Ready to Merge`
@yrimal
