### ISSUE TITLE
Allow self signed certs by default for localhost-like hosts

### ISSUE THREAD

**Issue by dianabarsan** [medic/cht-conf#586]
**What feature do you want to improve?**
--accept-self-signed-certs is just too long, I often mistype it and I mainly need to run this against local cht-core instances. 

**Describe the improvement you'd like**
Enable allowing self signed certs by default for localhost-like instances.

**Comment by garethbowen** [comment]
@dianabarsan Can this be closed now?

NB: Because this was marked "chore" it didn't trigger a release.

**Comment by dianabarsan** [comment]
Oh, sorry for forgetting to close it. I'm aware of the chore not triggering a release, it was deliberate.
