### ISSUE TITLE
Add SonarCloud configuration

### ISSUE THREAD

**Issue by andrablaj** [medic/cht-conf#605]
**Describe the improvement you'd like**
Add a file containing the repo-level SonarCloud configuration for `cht-conf`.

Similar to https://github.com/medic/cht-interoperability/pull/112.

You can find related documentation [here](https://docs.communityhealthtoolkit.org/contribute/code/static-analysis/).

**Comment by andrablaj** [comment]
@sugat009 I opened this ticket, in case you want to dig into how the SonarCloud setup works and set it up for this repo.

**Comment by sugat009** [comment]
Closing, as this has already been done through https://github.com/medic/cht-conf/pull/618
