### ISSUE TITLE
Incorrect command used for shell completion

### ISSUE THREAD

**Issue by binokaryg** [medic/cht-conf#632]
https://github.com/medic/cht-conf/blob/4c8571e2d5742bf30795bf916c83413008153d93/README.md?plain=1#L69

Running ` eval "$(cht-conf --shell-completion=bash)"`, gives this error:
```
cht-conf: command not found
```

It should be `cht` instead of `cht-conf`.

**Comment by garethbowen** [comment]
Merged. Thanks @binokaryg !
